/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#fbf9f9',
        'surface-dim': '#dbdad9',
        'surface-bright': '#fbf9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f3',
        'surface-container': '#efeded',
        'surface-container-high': '#e9e8e7',
        'surface-container-highest': '#e3e2e2',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#5d3f3c',
        'inverse-surface': '#303031',
        'inverse-on-surface': '#f2f0f0',
        'outline': '#926f6b',
        'outline-variant': '#e6bdb8',
        'surface-tint': '#c00014',
        'primary': '#ae0011',
        'uba-red': '#D71920',
        'on-primary': '#ffffff',
        'primary-container': '#d71920',
        'on-primary-container': '#ffece9',
        'inverse-primary': '#ffb4ab',
        'secondary': '#5f5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e4e2e1',
        'on-secondary-container': '#656464',
        'tertiary': '#525556',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#6b6d6e',
        'on-tertiary-container': '#eff0f1',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#fbf9f9',
        'on-background': '#1b1c1c',
        'surface-variant': '#e3e2e2',
        'deep-slate': '#333333',
      },
      fontFamily: {
        'montserrat': ['Montserrat', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
      },
      spacing: {
        'unit': '4px',
        'container-margin-mb': '20px',
        'container-margin-dt': '80px',
        'gutter': '16px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'section-gap': '64px',
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
      },
      boxShadow: {
        'soft': '0 16px 32px 0 rgba(51, 51, 51, 0.06)',
        'flexpay': '0 0 15px rgba(215, 25, 32, 0.1)',
      }
    },
  },
  plugins: [],
}
